// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBswqnjw_9msw5uwZGyyzHakRpq3TpEy-U',
    appId: '1:92476500762:web:704fd9bcfa659825a19aa3',
    messagingSenderId: '92476500762',
    projectId: 'resume-matching-jd',
    authDomain: 'resume-matching-jd.firebaseapp.com',
    storageBucket: 'resume-matching-jd.firebasestorage.app',
    measurementId: 'G-TT0ZDBM172',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAog98c2k1sz6rLWSeF19I0H0rqbBGgIn8',
    appId: '1:92476500762:android:5a5341e0546b28fda19aa3',
    messagingSenderId: '92476500762',
    projectId: 'resume-matching-jd',
    storageBucket: 'resume-matching-jd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOwm36moANKJnz3uoSMMHfFRiWEBtTxuk',
    appId: '1:92476500762:ios:bdfbf752673fe9c0a19aa3',
    messagingSenderId: '92476500762',
    projectId: 'resume-matching-jd',
    storageBucket: 'resume-matching-jd.firebasestorage.app',
    iosBundleId: 'com.example.resumeMatchingJd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOwm36moANKJnz3uoSMMHfFRiWEBtTxuk',
    appId: '1:92476500762:ios:bdfbf752673fe9c0a19aa3',
    messagingSenderId: '92476500762',
    projectId: 'resume-matching-jd',
    storageBucket: 'resume-matching-jd.firebasestorage.app',
    iosBundleId: 'com.example.resumeMatchingJd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBswqnjw_9msw5uwZGyyzHakRpq3TpEy-U',
    appId: '1:92476500762:web:6e3e114a0999df29a19aa3',
    messagingSenderId: '92476500762',
    projectId: 'resume-matching-jd',
    authDomain: 'resume-matching-jd.firebaseapp.com',
    storageBucket: 'resume-matching-jd.firebasestorage.app',
    measurementId: 'G-QF5FCSMG8T',
  );
}
